<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Admin" ignored="0" name="Test" tests="3" failures="1" timestamp="30 Apr 2023 04:20:24 GMT" time="79.886" errors="0">
  <testcase name="test1" time="21.763" classname="TestCases.LoginTest"/>
  <testcase name="test2" time="24.514" classname="TestCases.LoginTest"/>
  <testcase name="test4" time="0.625" classname="TestCases.LoginTest">
    <failure type="com.codoid.products.exception.FilloException" message="data table is not found">
      <![CDATA[com.codoid.products.exception.FilloException: data table is not found
at com.codoid.products.fillo.SelectExcelUtil.runSelectQuery(SelectExcelUtil.java:57)
at com.codoid.products.fillo.Select.getRecordset(Select.java:61)
at com.codoid.products.fillo.Connection.executeQuery(Connection.java:64)
at TestCases.LoginTest.test4(LoginTest.java:40)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- Test -->
